name: دانلود مدل NLLB-200 فارسی

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install huggingface_hub
      - run: mkdir -p models
      - run: huggingface-cli download persiannlp/mt5-small-parsinlu-opus-translation_fa_en --local-dir ./model
      - uses: actions/upload-artifact@v4
        with:
          name: nllb-model
          path: ./models
