name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Project
        run: |
          mkdir -p dist
          echo "build version: ${GITHUB_REF_NAME}" > dist/version.txt

      - name: Create Archive
        run: |
          sudo apt-get update && sudo apt-get install -y zstd
          tar -cf dist.tar -C dist/ .
          zstd -T0 -19 -o dist.tar.zst dist.tar

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist.tar.zst"
          generateReleaseNotes: true
          draft: false
          prerelease: false
