name: "Download Artifact from Previous Run"

on:
  workflow_dispatch:

jobs:
  download_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from previous workflow
        uses: dawidd6/action-download-artifact@v6
        with:
          # می‌توانید از نام فایل workflow اصلی استفاده کنید
          workflow: download.yml
          # شماره اجرای موفق (که در لیست می‌بینید)
          run_id: 9
          # نام دقیق Artifact (همان bert-model)
          name: bert-model
          # مسیری که فایل‌ها در آن ذخیره شوند
          path: ./downloaded-model

      - name: Upload as new artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-new-model
          path: ./downloaded-model
